[env:mindaq]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_DFU_ON_BOOT=0

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library

build_src_filter =
  -<*>
  +<main.cpp>

board_build.partitions = default.csv #helps not boot into uf2 factory mode

upload_protocol = esptool
upload_port = /dev/cu.usbmodem1101
upload_resetmethod = usb_serial_jtag
; upload_speed = 115200

monitor_port = /dev/cu.usbmodem1101
monitor_speed = 2000000
; monitor_dtr = 0
; monitor_rts = 0
monitor_filters = esp32_exception_decoder

[env:cdc_stream_test]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_DFU_ON_BOOT=0

build_src_filter =
  -<*>
  +<cdc_stream_test.cpp>

board_build.partitions = default.csv

upload_protocol = esptool
upload_port = /dev/cu.usbmodem1101
upload_resetmethod = usb_serial_jtag

monitor_port = /dev/cu.usbmodem1101
monitor_speed = 2000000

[env:adc_32ksps_test]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_DFU_ON_BOOT=0

build_src_filter =
  -<*>
  +<adc_32ksps_test.cpp>

board_build.partitions = default.csv

upload_protocol = esptool
upload_port = /dev/cu.usbmodem101
upload_resetmethod = usb_serial_jtag

monitor_port = /dev/cu.usbmodem101
monitor_speed = 2000000

[env:ft_raw_stream]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_DFU_ON_BOOT=0

build_src_filter =
  -<*>
  +<ft_raw_stream.cpp>

board_build.partitions = default.csv

upload_protocol = esptool
upload_port = /dev/cu.usbmodem101
upload_resetmethod = usb_serial_jtag

monitor_port = /dev/cu.usbmodem101
monitor_speed = 2000000

[env:capture_fw]
platform = espressif32
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_DFU_ON_BOOT=0

build_src_filter =
  -<*>
  +<capture_fw.cpp>

board_build.partitions = default.csv

upload_protocol = esptool
upload_port = /dev/cu.usbmodem101
upload_resetmethod = usb_serial_jtag

monitor_port = /dev/cu.usbmodem101
monitor_speed = 2000000
